(part "CSS-1210TB"
    (packageRef "CSS1210TB")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "MH1" (symbPinId 4) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 5) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "229-CSS-1210TB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nidec-Components/CSS-1210TB?qs=XeJtXLiO41RuZ%252BgY2j5i0A%3D%3D")
    (property "Manufacturer_Name" "Nidec Copal")
    (property "Manufacturer_Part_Number" "CSS-1210TB")
    (property "Description" "SWITCH SLIDE SPDT 100MA 12V")
    (property "Datasheet_Link" "https://www.nidec-copal-electronics.com/e/catalog/switch/css.pdf")
    (property "symbolName1" "CSS-1210TB")
)
